In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

# 10th september

# pytorch

In [2]:
import torch
torch.cuda.is_available()


False

In [22]:
import torch
a=torch.tensor([2,4,6,8])
print(a)
print(a.numel())
print(a.size())
print(a.ndim)
print(a.shape)
print(a.dtype)
print(torch.ones(2,3,dtype=int))
print(torch.zeros(2,2,dtype=int))
print(torch.arange(5,16,2))
print(torch.range(5,16,2))

tensor([2, 4, 6, 8])
4
torch.Size([4])
1
torch.Size([4])
torch.int64
tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[0, 0],
        [0, 0]])
tensor([ 5,  7,  9, 11, 13, 15])
tensor([ 5.,  7.,  9., 11., 13., 15.])


/tmp/ipykernel_58/2547572055.py:12: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  print(torch.range(5,16,2))


In [28]:
print(torch.rand(3,5))
print(torch.randn(3,5))

tensor([[0.0954, 0.0522, 0.2297, 0.2201, 0.4388],
        [0.0623, 0.2092, 0.6784, 0.9596, 0.8568],
        [0.8797, 0.5482, 0.5498, 0.9699, 0.9011]])
tensor([[-0.4189,  0.6478, -0.4052, -0.2308, -0.5468],
        [ 0.3471, -0.1310, -0.4264,  0.7095,  0.1709],
        [-0.6162, -0.6884,  0.8648, -0.3925, -0.1847]])


In [34]:
print(torch.full((2,3),8))

tensor([[8, 8, 8],
        [8, 8, 8]])


In [58]:
import torch
a=torch.tensor([[18,36,54,78],[36,94,72,81],[24,56,79,3],[1,2,3,4]])
print(a)
print(a[1])
print(a[2])
print(a[[2,3]])
print(a[[2,3],2])
print(a[[0,1,2],[1,2,3]])
print(a[2,1])
print(a[2:4,2:4])
print(a[1:3,1:3])


tensor([[18, 36, 54, 78],
        [36, 94, 72, 81],
        [24, 56, 79,  3],
        [ 1,  2,  3,  4]])
tensor([36, 94, 72, 81])
tensor([24, 56, 79,  3])
tensor([[24, 56, 79,  3],
        [ 1,  2,  3,  4]])
tensor([79,  3])
tensor([36, 72,  3])
tensor(56)
tensor([[79,  3],
        [ 3,  4]])
tensor([[94, 72],
        [56, 79]])
tensor([], size=(1, 0), dtype=torch.int64)


# operations

In [60]:
import torch
a=torch.tensor([[[18,36,54,78],[36,94,72,81]],[[24,56,79,3],[1,2,3,4]]])
print(a)

tensor([[[18, 36, 54, 78],
         [36, 94, 72, 81]],

        [[24, 56, 79,  3],
         [ 1,  2,  3,  4]]])


In [74]:
import torch
a=torch.tensor([[1,2],[5,6]])
b=torch.tensor([[7,8],[11,12]])
print(a,b)
print(torch.add(a,b))
print(torch.subtract(a,b))
print(torch.multiply(a,b))
print(torch.divide(a,b))
print(a@b)
print(torch.mul(a,b))


tensor([[1, 2],
        [5, 6]]) tensor([[ 7,  8],
        [11, 12]])
tensor([[ 8, 10],
        [16, 18]])
tensor([[-6, -6],
        [-6, -6]])
tensor([[ 7, 16],
        [55, 72]])
tensor([[0.1429, 0.2500],
        [0.4545, 0.5000]])
tensor([[ 29,  32],
        [101, 112]])
tensor([[ 7, 16],
        [55, 72]])


In [82]:
import torch
a=torch.tensor([[1,2],[5,6]])
b=torch.tensor([[7,8],[11,12]])
print(a,b)
print(torch.flip(a,dims=[0]))
print(torch.flip(b,dims=[1]))
print(torch.flip(b,dims=[0,1]))
print(torch.flip(b,dims=[1,0]))

tensor([[1, 2],
        [5, 6]]) tensor([[ 7,  8],
        [11, 12]])
tensor([[5, 6],
        [1, 2]])
tensor([[ 8,  7],
        [12, 11]])
tensor([[12, 11],
        [ 8,  7]])
tensor([[12, 11],
        [ 8,  7]])


In [90]:
import torch
a=torch.tensor([1,2,111,11,89])
print(a)
print(a.argmax())
print(a.max())
print(torch.max(a))
print(torch.argmax(a))

tensor([  1,   2, 111,  11,  89])
tensor(2)
tensor(111)
tensor(111)
tensor(2)


In [89]:
import torch
a=torch.tensor([1,2,111,11,89])
print(a)
print(a.argmin())
print(a.min())
print(torch.min(a))
print(torch.argmin(a))

tensor([  1,   2, 111,  11,  89])
tensor(0)
tensor(1)
tensor(1)
tensor(0)


In [96]:
import torch
AI=torch.tensor([40,60,30,70,95])
print(AI>=70)
print(AI[AI>=70])
print(AI[AI<35])

tensor([False, False, False,  True,  True])
tensor([70, 95])
tensor([30])
